server:
  port: 8081

spring:
  datasource:
    username: root
    password: zero
    url: jdbc:mysql://localhost:3306/employee_db
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: EMPLOYEE-SERVICE
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/